app/models/base.py
import uuid
import datetime

from sqlalchemy_utils import UUIDType
from flask_sqlalchemy import event, SessionBase
from flask import current_app

from app.database import db


class BaseModel(db.Model):
    __abstract__ = True

    id = db.Column(UUIDType(binary=False), primary_key=True)

    created_at = db.Column(db.Float, nullable=False)
    updated_at = db.Column(db.Float, nullable=True)

    def reload(self):
        db.session.refresh(self)

    def save(self):
        db.session.commit()

    def create(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def delete_all(cls):
        try:
            db.session.query(cls).delete()
            db.session.commit()
        except Exception as e:
            current_app.logger.info(e)
            db.rollback()
        return


@event.listens_for(SessionBase, "before_flush")
def before_flush_handler(session, flush_context, instances):
    for obj in session.new:
        obj.id = uuid.uuid1()
        obj.created_at = datetime.datetime.utcnow().timestamp()

    for obj in session.dirty:
        obj.updated_at = datetime.datetime.utcnow().timestamp()

app/models/trip.py
from app.database import db
from .base import BaseModel


class Trip(BaseModel):
    __tablename__ = 'trip'

    name = db.Column(db.String, nullable=True)
    coordinates = db.Column(db.JSON, nullable=False)
    color = db.Column(db.String, nullable=True)

app/models/user.py
from flask_login import UserMixin

from app.database import db
from app.models.base import BaseModel


class User(BaseModel, UserMixin):
    __tablename__ = 'user'

    username = db.Column(db.String, nullable=False)
    password = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=4)])
    password = PasswordField('Password', validators=[
        DataRequired(),
        EqualTo('confirm_password', message='Passwords must match'),
        Length(min=6)
    ])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), Length(min=6)])
    email_address = StringField('email_address', validators=[DataRequired()])


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=4)])
    password = PasswordField('Password', validators=[DataRequired()])

app/__init__.py
from flask import Flask
from flask_login import LoginManager

from app.database import db
from config import config
from app.views import home_bp
from app.finders.user_finder import UserFinder
from .api.routes import api_v1, api


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    api.init_app(app)
    app.register_blueprint(api_v1)
    app.register_blueprint(home_bp)
    login_manager = LoginManager(app)

    if app.debug:
        app.logger.setLevel("DEBUG")
    else:
        app.logger.setLevel("INFO")

    login_manager.login_view = "home.home"
    login_manager.user_loader(UserFinder.get_from_id)
    app.app_context().push()
    return app

app/api/routes.py
from flask import Blueprint, make_response
from flask_restful import Api

from app.api.resources import Trip, Trips

api_v1 = Blueprint('api_v1', __name__, url_prefix='/api/v1')
api = Api(api_v1)

api.add_resource(Trip, '/trips/<trip_id>')
api.add_resource(Trips, '/trips')

app/database/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_tables():
    db.create_all()


def drop_tables():
    db.reflect()
    db.drop_all()

app/views.py
from flask import Blueprint, render_template, current_app, redirect, url_for, flash, request
from flask_login import login_required, current_user, login_user, logout_user

from app.forms import LoginForm, RegisterForm
from app.handlers.user_handler import UserHandler

home_bp = Blueprint('home', __name__)


@home_bp.route('/user/trips')
@login_required
def user_index():
    return render_template('user/home.html',
                           basil_api_endpoint=current_app.config['BASIL_API_ENDPOINT'],
                           gmaps_api_key=current_app.config['GMAPS_API_KEY'])


@home_bp.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('home.user_index'))

    login_form = LoginForm()
    return render_template('homepage.html', form=login_form)


@home_bp.route("/login", methods=['POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = UserHandler.validate_user(form.username.data, form.password.data)
        if user:
            login_user(user)
            return redirect(url_for('home.user_index'))

    flash('Invalid credentials :(')
    return redirect(url_for('home.home'))


@home_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home.user_index'))

    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = UserHandler.create(
                username=form.username.data,
                email=form.username.data,
                password=form.password.data
            )
            login_user(user)
            return redirect(url_for('home.user_index'))
        else:
            flash('Dude, get your shit together')

    return render_template('register.html', form=form)


@home_bp.route('/logout', methods=['POST'])
def logout():
    logout_user()
    return redirect(url_for('home.home'))

app/templates/base.html
<!doctype html>
<head>
    {% block head %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    	<title>{% block title %}{% endblock %}</title>
        <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
        <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    {% endblock %}
</head>
<body>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class=flashes>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    {% block body %}{% endblock %}
</body>

app/templates/home.html
{% extends 'base.html' %}
{% block body %}
    <div class="map-header center">
        <div class="flex-row">
            <div class="flex-row-item map-name">Europe</div>
            <div class="flex-row-item color-picker flex-row">
                <!--Red-->
                <div class="color-picker-color active" data-color="#ff0000" style="background-color:red;"></div>
                <!--Blue-->
                <div class="color-picker-color" data-color="#0000FF" style="background-color:blue;"></div>
                <!--Lime Green-->
                <div class="color-picker-color" data-color="#33cc33" style="background-color: #33cc33"></div>
                <!--Yellow-->
                <div class="color-picker-color" data-color="#ffff00" style="background-color: yellow"></div>
                <!--Turquoise-->
                <div class="color-picker-color" data-color="#00F5FF" style="background-color: #00F5FF"></div>
                <!--Black-->
                <div class="color-picker-color" data-color="#000000" style="background-color: black"></div>
                <!--Magenta-->
                <div class="color-picker-color" data-color="#ff00ff" style="background-color: #ff00ff"></div>
                <!--Orange-->
                <div class="color-picker-color" data-color="#ffa500" style="background-color: #ffa500"></div>
                <!--Steel blue-->
                <div class="color-picker-color" data-color="#4682B4" style="background-color: #4682B4"></div>
                <!--Purple-->
                <div class="color-picker-color" data-color="#800080" style="background-color: #800080"></div>
            </div>
            <div class="flex-row-item remove-trips">
                <a id="delete-trips" class="remove-trips button button-rounded button-small">Reset</a>
            </div>
        </div>
    </div>
    <div class="map-container">
        <canvas id="canvas-map"></canvas>
        <div id="map"></div>
    </div>
    <div class="popup">
        <div class="popup-content">
            <div class="popup-message">
                Wanna save the trip?
            </div>
            <div class="popup-options">
                <a id="save-trip" class="button button-rounded button-primary button-small">Yupi!</a>
                <a id="cancel-trip" class="button button-rounded button-small">Nope.avi</a>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
							integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    <script>
          function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 4,
                center: {lat: 52.519325, lng:13.392709}, //Europe
                clickableIcons: false,
                disableDefaultUI: true,
                disableDoubleClickZoom: true,
                draggable: false
            });
          }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key={{gmaps_api_key }}&callback=initMap">
    </script>
    <script>
        $(document).ready(function(){
            var canvas = document.getElementById("canvas-map");
            var ctx = canvas.getContext("2d");
            canvas.width = $("#map").width();
            canvas.height =  $("#map").height();
            ctx.imageSmoothingEnabled = true;


            var coordinates = new Array();
            var trips = new Array();
            var paint = false;
            var $map = $("#canvas-map");

            ctx.strokeStyle = $(".color-picker").find('.active').data('color');
            ctx.lineWidth = 3;
            ctx.lineJoin = 'round';
            ctx.lineCap = 'round';

             $.ajax({
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                url: "http://{{ basil_api_endpoint }}/api/v1/trips"
            }).success(function(data){
                trips = data;
                drawTrips(trips);
            });


            $map.bind('mousedown', function(e) {
                if (!paint){
                    paint  = true;
                }
            });

            $map.mousemove(function(e){
                if (paint) {
                    var x = e.pageX - this.offsetLeft;
                    var y = e.pageY - this.offsetTop - $(".map-header").height();
                    coordinates.push({"x": x, "y":y});
                    if (coordinates.length >= 6) {
                        drawTrip(coordinates);
                    }
                }
            });

            $map.bind('mouseup', function(e){
                if (paint) {
                    $(".popup").css("position", "absolute");
                    $(".popup").css("left", e.pageX - this.offsetLeft);
                    $(".popup").css("top", e.pageY - this.offsetTop);
                    $(".popup").fadeIn(1000);
                }
                paint = false;
            });

            $map.bind('mouseleave', function(e){
               paint = false;
               ctx.closePath();
            });

            $("#save-trip").on('click', function(){
                color = $(".color-picker").find('.active').data('color');
                $.ajax({
                    type: "POST",
                    headers: {"Content-Type": "application/json"},
                    url: "http://"+"{{ basil_api_endpoint }}"+"/api/v1/trips",
                    data: JSON.stringify({"coordinates": coordinates, "color": color})
                }).success(function() {
                    $(".popup").fadeOut(500);
                    ctx.closePath();
                    trips.push({"coordinates": coordinates, "color": color});
                    coordinates = new Array();
                });
            });

            $("#cancel-trip").on('click', function(){
                $(".popup").fadeOut(500);
                coordinates = new Array();
                ctx.clearRect(0,0,canvas.width,canvas.height);
                drawTrips(trips);
            });

            $("#delete-trips").on('click', function(){
                $.ajax({
                    method: 'DELETE',
                    headers: {'Content-Type': 'application/json'},
                    url: "http://{{ basil_api_endpoint }}/api/v1/trips"
                    }).success(function(data){
                        coordinates = new Array();
                        trips = new Array();
                        ctx.clearRect(0,0,canvas.width,canvas.height);
                    });
            });

            $(".color-picker-color").click(function(){
               if (!$(this).hasClass('active')) {
                   $(".color-picker").find('.active').removeClass('active');
                   $(this).addClass("active");
                   ctx.strokeStyle = $(this).data('color');
               }
            });

            function drawTrips(trips){
                trips.forEach(function(trip){
                   drawTrip(trip.coordinates, trip.color);
                });
            }

            function drawTrip(coordinates, color){
                ctx.strokeStyle = color;
                ctx.beginPath();
                ctx.moveTo(coordinates[0].x, coordinates[0].y);
                for (var i = 1; i < coordinates.length - 2; i++) {
                    var c = (coordinates[i].x + coordinates[i + 1].x) / 2;
                    var d = (coordinates[i].y + coordinates[i + 1].y) / 2;
                    ctx.quadraticCurveTo(coordinates[i].x, coordinates[i].y, c, d)
                }
                ctx.quadraticCurveTo(coordinates[i].x, coordinates[i].y,
                    coordinates[i + 1].x, coordinates[i + 1].y);
                ctx.stroke();
                ctx.closePath();
            }

        });
    </script>

{% endblock %}

app/templates/homepage.html
{% extends 'base.html' %}
{% block title %} Basil - Login{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    Hello world
    <form method="POST" action="/login">
    {{ form.csrf_token }}
    {{ form.username }}
    {{ form.password }}
    <input type="submit" value="Login">
    <small>Not logged in? <a href="{{ url_for('home.register')}}">Register!</a></small>
</form>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% block title %} Basil - Login{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    Let's register!
    <form method="POST" action="/register">
    {{ form.csrf_token }}
    Username: {{ form.username }}
    Email Address:{{ form.email_address }}
    Password: {{ form.password }}
    Confirm Password: {{ form.confirm_password }}
    <input type="submit" value="Register">
</form>
{% endblock %}

app/templates/user/home.html
{% extends 'base.html' %}
{% block title %}Basil{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/buttons.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="map-header center">
        <div class="flex-row">
            <div class="flex-row-item map-name">Europe</div>
            <div class="flex-row-item color-picker flex-row">
                <!--Red-->
                <div class="color-picker-color active" data-color="#ff0000" style="background-color:red;"></div>
                <!--Blue-->
                <div class="color-picker-color" data-color="#0000FF" style="background-color:blue;"></div>
                <!--Lime Green-->
                <div class="color-picker-color" data-color="#33cc33" style="background-color: #33cc33"></div>
                <!--Yellow-->
                <div class="color-picker-color" data-color="#ffff00" style="background-color: yellow"></div>
                <!--Turquoise-->
                <div class="color-picker-color" data-color="#00F5FF" style="background-color: #00F5FF"></div>
                <!--Black-->
                <div class="color-picker-color" data-color="#000000" style="background-color: black"></div>
                <!--Magenta-->
                <div class="color-picker-color" data-color="#ff00ff" style="background-color: #ff00ff"></div>
                <!--Orange-->
                <div class="color-picker-color" data-color="#ffa500" style="background-color: #ffa500"></div>
                <!--Steel blue-->
                <div class="color-picker-color" data-color="#4682B4" style="background-color: #4682B4"></div>
                <!--Purple-->
                <div class="color-picker-color" data-color="#800080" style="background-color: #800080"></div>
            </div>
            <div class="flex-row-item remove-trips">
                <a id="delete-trips" class="remove-trips button button-rounded button-small">Reset</a>
            </div>
            <div class="flex-row-item remove-trips">
                <form method="POST" action="/logout">
                     <input type="submit" value="Logout" class="button button-rounded button-caution button-small">
                </form>
            </div>
        </div>

    </div>
    <div class="map-container">
        <canvas id="canvas-map"></canvas>
        <div id="map"></div>
    </div>
    <div class="popup">
        <div class="popup-content">
            <div class="popup-message">
                Wanna save the trip?
            </div>
            <div class="popup-options">
                <a id="save-trip" class="button button-rounded button-primary button-small">Yupi!</a>
                <a id="cancel-trip" class="button button-rounded button-small">Nope.avi</a>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
							integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    <script>
          function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 4,
                center: {lat: 52.519325, lng:13.392709}, //Europe
                clickableIcons: false,
                disableDefaultUI: true,
                disableDoubleClickZoom: true,
                draggable: false
            });
          }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key={{gmaps_api_key }}&callback=initMap">
    </script>
    <script>
        $(document).ready(function(){
            var canvas = document.getElementById("canvas-map");
            var ctx = canvas.getContext("2d");
            canvas.width = $("#map").width();
            canvas.height =  $("#map").height();
            ctx.imageSmoothingEnabled = true;


            var coordinates = new Array();
            var trips = new Array();
            var paint = false;
            var $map = $("#canvas-map");

            ctx.strokeStyle = $(".color-picker").find('.active').data('color');
            ctx.lineWidth = 3;
            ctx.lineJoin = 'round';
            ctx.lineCap = 'round';

             $.ajax({
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                url: "http://{{ basil_api_endpoint }}/api/v1/trips"
            }).success(function(data){
                trips = data;
                drawTrips(trips);
            });


            $map.bind('mousedown', function(e) {
                if (!paint){
                    paint  = true;
                }
            });

            $map.mousemove(function(e){
                if (paint) {
                    var x = e.pageX - this.offsetLeft;
                    var y = e.pageY - this.offsetTop - $(".map-header").height();
                    coordinates.push({"x": x, "y":y});
                    if (coordinates.length >= 6) {
                        drawTrip(coordinates);
                    }
                }
            });

            $map.bind('mouseup', function(e){
                if (paint) {
                    $(".popup").css("position", "absolute");
                    $(".popup").css("left", e.pageX - this.offsetLeft);
                    $(".popup").css("top", e.pageY - this.offsetTop);
                    $(".popup").fadeIn(1000);
                }
                paint = false;
            });

            $map.bind('mouseleave', function(e){
               paint = false;
               ctx.closePath();
            });

            $("#save-trip").on('click', function(){
                color = $(".color-picker").find('.active').data('color');
                $.ajax({
                    type: "POST",
                    headers: {"Content-Type": "application/json"},
                    url: "http://"+"{{ basil_api_endpoint }}"+"/api/v1/trips",
                    data: JSON.stringify({"coordinates": coordinates, "color": color})
                }).success(function() {
                    $(".popup").fadeOut(500);
                    ctx.closePath();
                    trips.push({"coordinates": coordinates, "color": color});
                    coordinates = new Array();
                });
            });

            $("#cancel-trip").on('click', function(){
                $(".popup").fadeOut(500);
                coordinates = new Array();
                ctx.clearRect(0,0,canvas.width,canvas.height);
                drawTrips(trips);
            });

            $("#delete-trips").on('click', function(){
                $.ajax({
                    method: 'DELETE',
                    headers: {'Content-Type': 'application/json'},
                    url: "http://{{ basil_api_endpoint }}/api/v1/trips"
                    }).success(function(data){
                        coordinates = new Array();
                        trips = new Array();
                        ctx.clearRect(0,0,canvas.width,canvas.height);
                    });
            });

            $(".color-picker-color").click(function(){
               if (!$(this).hasClass('active')) {
                   $(".color-picker").find('.active').removeClass('active');
                   $(this).addClass("active");
                   ctx.strokeStyle = $(this).data('color');
               }
            });

            function drawTrips(trips){
                trips.forEach(function(trip){
                   drawTrip(trip.coordinates, trip.color);
                });
            }

            function drawTrip(coordinates, color){
                ctx.strokeStyle = color;
                ctx.beginPath();
                ctx.moveTo(coordinates[0].x, coordinates[0].y);
                for (var i = 1; i < coordinates.length - 2; i++) {
                    var c = (coordinates[i].x + coordinates[i + 1].x) / 2;
                    var d = (coordinates[i].y + coordinates[i + 1].y) / 2;
                    ctx.quadraticCurveTo(coordinates[i].x, coordinates[i].y, c, d)
                }
                ctx.quadraticCurveTo(coordinates[i].x, coordinates[i].y,
                    coordinates[i + 1].x, coordinates[i + 1].y);
                ctx.stroke();
                ctx.closePath();
            }

        });
    </script>

{% endblock %}